// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    DarkMode: typeof import('./src/components/DarkMode.vue')['default']
    MyImg: typeof import('./src/components/img/MyImg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    UCheckBox: typeof import('./src/components/ui/UCheckBox.vue')['default']
    UDanmaku: typeof import('./src/components/danmaku/UDanmaku.vue')['default']
    UEnter: typeof import('./src/components/danmaku/UEnter.vue')['default']
    UGift: typeof import('./src/components/danmaku/UGift.vue')['default']
    UGuardTag: typeof import('./src/components/ui/UGuardTag.vue')['default']
    URenderer: typeof import('./src/components/danmaku/URenderer.vue')['default']
    USlider: typeof import('./src/components/ui/USlider.vue')['default']
    USubscribe: typeof import('./src/components/danmaku/USubscribe.vue')['default']
    USuperChat: typeof import('./src/components/danmaku/USuperChat.vue')['default']
    USwitch: typeof import('./src/components/ui/USwitch.vue')['default']
    UWatch: typeof import('./src/components/danmaku/UWatch.vue')['default']
  }
}
