// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkMode: typeof import('./src/components/DarkMode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    UCheckBox: typeof import('./src/components/ui/UCheckBox.vue')['default']
    USlider: typeof import('./src/components/ui/USlider.vue')['default']
    USwitch: typeof import('./src/components/ui/USwitch.vue')['default']
  }
}
