// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/img/Avatar.vue')['default']
    DarkMode: typeof import('./components/DarkMode.vue')['default']
    Login: typeof import('./components/settings/Login.vue')['default']
    MyImg: typeof import('./components/img/MyImg.vue')['default']
    MyQrCode: typeof import('./components/img/MyQrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    UCheckBox: typeof import('./components/ui/UCheckBox.vue')['default']
    UColorPicker: typeof import('./components/ui/UColorPicker.vue')['default']
    UDanmaku: typeof import('./components/danmaku/UDanmaku.vue')['default']
    UEnter: typeof import('./components/danmaku/UEnter.vue')['default']
    UGift: typeof import('./components/danmaku/UGift.vue')['default']
    UGuardTag: typeof import('./components/danmaku/UGuardTag.vue')['default']
    UInputBtn: typeof import('./components/ui/UInputBtn.vue')['default']
    UMdInput: typeof import('./components/ui/UMdInput.vue')['default']
    UMessageProvider: typeof import('./components/ui/UMessageProvider.vue')['default']
    UMessageSender: typeof import('./components/send/UMessageSender.vue')['default']
    UMultiList: typeof import('./components/ui/UMultiList.vue')['default']
    URadio: typeof import('./components/ui/URadio.vue')['default']
    URenderer: typeof import('./components/danmaku/URenderer.vue')['default']
    UScDanmaku: typeof import('./components/superchat/UScDanmaku.vue')['default']
    USettingsBox: typeof import('./components/ui/USettingsBox.vue')['default']
    USlider: typeof import('./components/ui/USlider.vue')['default']
    USubscribe: typeof import('./components/danmaku/USubscribe.vue')['default']
    USuperChatFloat: typeof import('./components/superchat/USuperChatFloat.vue')['default']
    USuperChatPool: typeof import('./components/superchat/USuperChatPool.vue')['default']
    USuperChatTag: typeof import('./components/superchat/USuperChatTag.vue')['default']
    USwitch: typeof import('./components/ui/USwitch.vue')['default']
    UTabSelector: typeof import('./components/ui/UTabSelector.vue')['default']
    UTag: typeof import('./components/ui/UTag.vue')['default']
    UWatch: typeof import('./components/danmaku/UWatch.vue')['default']
    UWidget: typeof import('./components/UWidget.vue')['default']
  }
}
